version: '3.8'

services:
  lyrics-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./songs:/app/songs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py
